version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_MULTIPLE_DATABASES: "airflow,sample_data_source,sample_tableau"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - airflow

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - airflow
    depends_on:
      - zookeeper

  airflow-init:
    image: apache/airflow:2.1.2
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://devuser:devpasswd@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://devuser:devpasswd@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: kafka://kafka:9092
      AIRFLOW__SMTP__SMTP_HOST: mailhog
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_USER: ""
      AIRFLOW__SMTP__SMTP_PASSWORD: ""
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@example.com"
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow
    depends_on:
      - postgres
      - kafka
      - mailhog

  airflow-webserver:
    image: apache/airflow:2.1.2
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://devuser:devpasswd@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://devuser:devpasswd@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: kafka://kafka:9092
      AIRFLOW__SMTP__SMTP_HOST: mailhog
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_USER: ""
      AIRFLOW__SMTP__SMTP_PASSWORD: ""
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@example.com"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow
    depends_on:
      - postgres
      - airflow-init
      - kafka
      - mailhog

  airflow-scheduler:
    image: apache/airflow:2.1.2
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://devuser:devpasswd@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://devuser:devpasswd@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: kafka://kafka:9092
      AIRFLOW__SMTP__SMTP_HOST: mailhog
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_USER: ""
      AIRFLOW__SMTP__SMTP_PASSWORD: ""
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@example.com"
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow
    depends_on:
      - postgres
      - airflow-init
      - kafka
      - mailhog

  airflow-worker:
    image: apache/airflow:2.1.2
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://devuser:devpasswd@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://devuser:devpasswd@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: kafka://kafka:9092
      AIRFLOW__SMTP__SMTP_HOST: mailhog
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_USER: ""
      AIRFLOW__SMTP__SMTP_PASSWORD: ""
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@example.com"
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow
    depends_on:
      - postgres
      - airflow-init
      - kafka
      - mailhog

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - airflow

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - airflow

volumes:
  postgres_data:

networks:
  airflow:
    driver: bridge